pipeline {
	agent {
		node {
      		label 'jenkins-slave1.yvu.ch'
    	}
	}
	stages {
		stage('Build') {
			steps {
				sh 'echo Build'
				sh 'cd Gadgeothek; ./gradlew build'
			}
	    	post {
           	    success {
               	    archiveArtifacts '**/outputs/apk/*.apk'
                 }
                 always {
                    junit allowEmptyResults: true, testResults: '**/build/test-results/testDemoDebugUnitTest/*.xml'
                    publishHTML([allowMissing: true, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'Gadgeothek/app/build/reports', reportFiles: 'lint-results.html', reportName: 'Lint Results', reportTitles: ''])
                 }
             }
		}

		stage('End2End Tests') {
            steps {
		        sh '(cd Gadgeothek; ./gradlew connectedAndroidTest)'
		    }
		    post {
		        always { junit "Gadgeothek/app/build/outputs/androidTest-results/connected/flavors/DEMO/*.xml" }
		    }
		}

		stage('Package') {
		    steps {
		        sh 'echo Package'
		    }
		}
	}
	post {
	    always {
    	    cleanWs()
	    }
	}
}
