pipeline {
	agent { 
		node {
      		label 'jenkins-slave1.yvu.ch'
    	}
	}
	stages {
		stage('Build') {
			steps {
				sh '(cd Gadgeothek; ./gradlew build)'
			}
		}

/*		stage('End2End Tests') {
		    steps {
		        sh '(cd Gadgeothek; ./gradlew connectedAndroidTest)'
		    }
		    post {
		        always { junit "Gadgeothek/app/build/outputs/androidTest-results/connected/flavors/DEMO/*.xml" }
		    }
		}
*/

		stage('Package') {
		    steps {
		        sh './Gadgeothek/scripts/package-android.sh'
		    }
		    post {
		    	success { archiveArtifacts 'Gadgeothek/app/build/outputs/apk/Gadgeothek.apk' }
		    }
		}
	}
}
