pipeline {
	agent { 
		node {
      		label 'jenkins-slave1.yvu.ch'
    	}
	}
	stages {
		stage('Build') {
			steps {
				sh '(cd Gadgeothek; ./gradlew build)'
			}
		}

		stage('End2End Tests') {
		    steps {
		        sh '(cd Gadgeothek; ./gradlew connectedAndroidTest)'
		    }
		}

		stage('Package') {
		    steps {
		        sh 'echo Package'
		    }
		}
	}
}
